import { Container } from "@nextui-org/react";
import Head from "next/head";
import NavBar from "../ui/NavBar";

const CustomLayout = ({children, title }) => {
    return (
        <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        
        <main style={{padding: "0 20px",minHeight: "84vh" }}>{children}</main>
        <footer>
            <Container 
            fluid 
            justify = "flex-end"
            css={{
                marginTop: "30px",
                height: '100px',
                display: "flex",
                width: "100%",
                bgColor: '$gray100',
                }}
            >
                <div className="footer-container">
                    <p>Todos los Derechos Reservados</p>
                </div>
            </Container>
        </footer>
        </>
    );
};

export default CustomLayout;